" load Pathogen (to load plugins)
call pathogen#infect()

" plugins on and turn on indentation
filetype on
filetype plugin on
filetype indent on

" How many columns a tab counts for (not used)
set tabstop=8

" Actually check the start and end of the file to determine filetype
set modeline

" use modern modern mode 
set nocompatible

" lines wrap 2 spaces from the edge
set bs=2

" switch buffers without writing to disk
set hidden

" set terminal title to filename
set title

" remember more commands and search patterns
set history=1000

" Case-smart search
set ignorecase
set smartcase
set incsearch

set scrolloff=3
set wildmode=longest,list

"Turn off the bell sound
set visualbell

" show the rule
set ruler

" Enable syntax highlighting
syntax on

" Set jj to exit insert mode
imap jj <Esc>

" Set code folding
set foldmethod=indent
set foldlevel=99

let g:SuperTabDefaultCompletionType = "context"

" Set F5 to be the date in normal and insert mode
:nnoremap <F5> "=strftime("%c")<CR>P
:inoremap <F5> <C-R>=strftime("%c")<CR>

" Paste mode with F3
set pastetoggle=<F3>

" Markdown syntax highlighting
au BufRead,BufNewFile *.md set filetype=markdown
au BufRead,BufNewFile *.coffee set filetype=coffee
