# Use Vi commands in the terminal
set -o vi

# Setup aliases
alias ll="ls -la"

# Setup prompt
export PS1="\u@\h:\w> "

# If work laptop, show hosts in SSH config
if [ $(hostname) = "workdev01" ]
then
	alias hosts="grep 'Host\ ' ~/.ssh/config | cut -d' ' -f2 | sort"
fi

# added by duckpan installer
eval $(perl -I/home/lex/perl5/lib/perl5 -Mlocal::lib)

