# Use Vi commands in the terminal
set -o vi

# Setup aliases
alias ll="ls -la"

# Git aliases
alias gc="git commit -a -m "
alias gp="git push"
alias gs="git status"
alias gb="git branch"
alias gd="git diff"
alias gu="git pull"

# Setup prompt
export PS1="\u@\h:\w> "

# added by duckpan installer
eval $(perl -I/home/lex/perl5/lib/perl5 -Mlocal::lib)

# Other env
export DEBEMAIL="lex.toumbourou@team.telstra.com"
export DEBFULLNAME="Lex Toumbourou"
