# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# Use Vi commands in the terminal
set -o vi

# Setup aliases
alias ll="ls -la"
alias la='ls -A'
alias l='ls -CF'
alias c='clear'

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Git aliases
alias gc="git commit -m "
alias ga="git add "
alias gp="git push"
alias gs="git status"
alias gb="git branch"
alias gd="git diff"
alias gu="git pull"

# Setup prompt
export PS1="\u@\h:\w> "

# Other env
export DEBEMAIL="lex.toumbourou@team.telstra.com"
export DEBFULLNAME="Lex Toumbourou"
export PYTHONSTARTUP=~/.pythonrc

# Unlimited history. I'll manage it myself. 
HISTSIZE=""
HISTFILESIZE=""

# Maintain history across windows and tabs
shopt -s histappend

# Support bash completion
if [ -f /etc/bash_completion ]
then
    . /etc/bash_completion
fi

# Use keychain to manage passphrase
eval `keychain --eval id_rsa`

# Host specific settings
source ~/.host.bashrc

# added by travis gem
[ -f ~/.travis/travis.sh ] && source ~/.travis/travis.sh
